Funcion para encriptar los datos del usuario en la base 5
pythonmurcia/gitcollab pull request #20
Opened 2020-10-03 11:59 UTC by iracaballero

Al final lo he hecho con el modulo cryptography de python, no lo conocia y me ha parecido super interesante y facil de usar, muchas gracias por la recomendación.
Espero que esté todo correcto.

2020-10-03 15:41 UTC, PabloCorbCon requested changes
Hey!
El código está mucho mejor que antes
Te **he dejado un par de comentarios para mantener la escabilidad del proyecto**, intenta hacerlos.
No tienes que cerrar el pull request, sino hacer commit sobre el mismo y nosotros le hacemos merge.
Buena suerte!

2020-10-03 15:41 UTC, PabloCorbCon commented on db/security.py
> +def generar_clave():
vamos a intentar mantener el nombre de las variables y funciones en ingles para mantener la escabilidad del proyecto, cambia `generar_clave()` port `generate_key()`

2020-10-03 15:41 UTC, PabloCorbCon commented on db/security.py
> +    clave = Fernet.generate_key()
Cambia la variable `clave` por `key`

2020-10-03 15:41 UTC, PabloCorbCon commented on db/security.py
> +        archivo_clave.write(clave)
Cambia el nombre del archivo `clave.key` a `key.key` o como gustes.

2020-10-03 15:41 UTC, PabloCorbCon commented on db/security.py
> +def cargar_clave():
Cambia el nombre de la función `cargar_clave()` por `load_key()`

2020-10-03 15:41 UTC, PabloCorbCon commented on db/security.py
> +    return open("clave.key").read()
Cambia el nombre del archivo `clave.key` a `key.key`

2020-10-03 16:26 UTC, iracaballero commented
@PabloCorbCon ya lo he cambiado a inglés, a partir de ahora lo pondré todo así (por si me quieres ir asignando la issue 13).
Ya siento todos los fallos que hago aunque la verdad es que estoy aprendiendo un montón, asi que muchas gracias por la paciencia, de verdad.

2020-10-03 18:39 UTC, PabloCorbCon requested changes
Perfecto, muchísimas gracias por la contribución. 
Una última cosita, ¿**quieres documentar las funciones** o prefieres que habramos otro issue con esa tarea?  bajo tu decisión jaja.
También me gustaría saber si te animas con #13 
Muchas gracias por elegir GitCollab como el primer proyecto al que contribuyes, ¡espero que no sea el último!

2020-10-04 10:59 UTC, iracaballero commented
Vale sin problema las puedo documentar (esto lo hago en el inglés o en castellano?, a mí me da igual la verdad).

Y sisi me animo con la #13, si me la puedes asignar.

2020-10-04 11:03 UTC, PabloCorbCon commented
Documenta en castellano, las funciones se crean en ingles para "mantener un poco la escabilidad", pero la documentación al  fin y al cabo la vamos a utilizar para que el resto de programadores entiendan el  propósito y funcionamiento de las funciones, clases...

Perfecto, voy a asignarte #13.

2020-10-04 12:21 UTC, iracaballero commented
@PabloCorbCon ya están documentadas las funciones

2020-10-04 13:06 UTC, PabloCorbCon approved these changes
@iracaballero perfecto! Muchas gracias por tu contribucion. Te hemos añadido al archivo [colaborators.md](https://github.com/pythonmurcia/gitcollab/blob/master/colaborators.md) del proyecto, pero no tengo ningun enlace que pueda ayudar a la gente a localizarte, si quieres añadir uno a la seccion `enlaces de interés` puedes hacer un pull request o abrir un issue y lo añadimos nosotros.

2020-10-04 13:07 UTC, merged